name: Build

on:
  push:
    tags: '*' # debug
  schedule:
    - cron: 0 3 5 * *
  workflow_dispatch:

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }} # Supplied by actions/create-release
      yearmonth: ${{ steps.time.outputs.yearmonth }}
    steps:
      - uses: actions/checkout@v3

      - name: Get current date and time
        env: 
          TZ: "Asia/Tokyo"
        id: time
        run: |
          echo "::set-output name=time::$(date +'%Y-%m-%d %H:%M') JST"
          echo "::set-output name=yearmonth::$(date +'%Y%m')"

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.time.outputs.yearmonth }}
          release_name: ${{ steps.time.outputs.time }}
          body: |-
            XTBook dictionary files (.xtbdict) generated at ${{ steps.time.outputs.time }}. You must extract them first with 7-Zip first.

            ${{ steps.time.outputs.time }} に自動生成された XTBook 辞書ファイル (.xtbdict) です。ダウンロードしたファイルは、最初に 7-Zip 等を用いて展開する必要があります。
          prerelease: true
  
  jawikibooks:
    name: Build Japanese Wikibooks
    needs: [create_release]
    runs-on: ubuntu-latest
    steps:
      - name: Prepare XTBook Converter
        run: |
          wget -O xtbookconv.7z https://github.com/watamario15/xtbook/releases/download/v0.2.6/xtbookconv.7z
          7z x xtbookconv.7z
          wget -O jawikibooks.plist https://github.com/watamario15/dotfiles/raw/main/tools/info-plists/jawikibooks.plist
          wget -O XTBook https://github.com/watamario15/dotfiles/raw/main/tools/XTBook
          chmod +x XTBook
          sudo apt install -y mecab-ipadic libmecab2 libkakasi2
          ls -la $GITHUB_WORKSPACE # debug
          
      - name: Convert
        run: DICTDIR=$GITHUB_WORKSPACE MKXTBDIR=$GITHUB_WORKSPACE PLIST=$GITHUB_WORKSPACE ./XTBook wikimedia jawikibooks ${{ needs.create_release.outputs.yearmonth }}01
       
      - name: Release
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: jawikibooks-${{ needs.create_release.outputs.yearmonth }}01.xtbdict.7z
          asset_name: jawikibooks-${{ needs.create_release.outputs.yearmonth }}01.xtbdict.7z
          asset_content_type: application/x-7z-compressed
